MODEL:
  ARCH: resnet50
  METHOD: ProDe
SETTING:
  DATASET: office
  S: 1
  T: 0
  SEED: 2020
  OUTPUT_SRC: source
OPTIM:
  METHOD: SGD
  MOMENTUM: 0.9
  LR: 0.01
  WD: 1e-3
  NESTEROV: TRUE
TEST:
  BATCH_SIZE: 64
  MAX_EPOCH: 30
  INTERVAL: 15
ProDe:
  EPSILON : 1e-5
  GENT_PAR: 0.1
  ARCH : ViT-B/32
  TTA_STEPS : 1
  CTX_INIT : a_photo_of_a
  N_CTX : 4
  LOAD : None
  IIC_PAR: 1.3